name: Go

on:
  push:
    branches: [ "aula_5" ]
  pull_request:
    branches: [ "aula_5" ]

jobs:

  test:
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        OS: ['ubuntu-latest', 'windows-11']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.16

    - name: Test
      run: go test -v main_test.go

  build:
    needs: test
    runs-on: ${{ matrix.OS }}
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v main.go
